services:
  - redis-server
language: cpp
julia: 
  - 0.5
compiler:
  - clang
notifications:
  email: false
env:
  matrix:
    - JULIAVERSION="juliareleases"
    - JULIAVERSION="julianightlies"
before_install:
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/${JULIAVERSION} -y
  - sudo apt-get update -qq -y
  - sudo apt-get install libpcre3-dev julia -y
  - sudo apt-get install libhiredis-dev -y
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
script:
  - julia -e 'Pkg.init(); Pkg.clone(pwd()); Pkg.add("BinDeps"); Pkg.add("DataStructures"); Pkg.build("Redis"); Pkg.test("Redis", coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("Redis")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
